### ISSUE TITLE
Determine GitHub subscription to use for ampproject

### ISSUE THREAD

**Issue by mrjoro** [ampproject/wg-foundation-onboarding#14]
ampproject currently uses a legacy GitHub per-repository subscription, GitHub Bronze ($300/year for 10 private repos).  We no longer have any private repos, so we would be eligible for the legacy free for open source plan.

However, in order to take advantage of GitHub Actions we would need to switch to a non-legacy GitHub plan.

GitHub's pricing documentation is a bit unclear regarding what the options are for open source projects.  There is mention of [GitHub Team for OpenSource](https://github.com/pricing), but it's unclear whether this is free or has the same pricing as the regular GitHub Teams, which is $108/user/year.  (Because we add most contributors as members of the org, we currently have over 400 people, which would be ~$45k/year.)  I will investigate to find out more about what the options are for open source projects.

Relevant to this, the OpenJS Foundation is [reviewing how it manages foundation infrastructure](https://github.com/openjs-foundation/cross-project-council/issues/291), which references a [draft infrastructure services menu](https://docs.google.com/document/d/1yQgEMvnY0apAEYoiysfae7qqmbJAfd4eLgmGKviPZ_0/edit#heading=h.zcfr48sm80ds).

**Comment by mrjoro** [comment]
The [GitHub About organizations page](https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/about-organizations) indicates "A free option, GitHub Team for Open Source, with unlimited collaborators on unlimited public repositories."

I don't see this option in the ampproject org upgrade flow.  I'm reaching out to a GitHub contact to find out the right process.

**Comment by mrjoro** [comment]
I confirmed that we can upgrade to the free GitHub Teams for Open Source, but we first have to downgrade our current plan to the legacy "free for open source" plan.

I will make this change tomorrow.

**Comment by tobie** [comment]
This no longer seems relevant know that organizations have a free tier.
