### ISSUE TITLE
Determine how to handle responsible security disclosures after AMP is onboarded into OpenJS Foundation

### ISSUE THREAD

**Issue by mrjoro** [ampproject/wg-foundation-onboarding#21]
Currently AMP accepts responsible security disclosures through the [Google Application Security program](https://www.google.com/about/appsecurity/) as documented in [README.md](https://github.com/ampproject/amphtml/blob/master/README.md).

We should determine whether this is still feasible/desirable when AMP is onboarded to the OpenJS Foundation, and if not what the alternative is.

/cc @ampproject/wg-foundation-onboarding

**Comment by tobie** [comment]
I’ve been tracking this on the foundation side here: https://github.com/openjs-foundation/cross-project-council/issues/326

**Comment by tobie** [comment]
Closing this as a duplicate of https://github.com/ampproject/wg-security-privacy/issues/2. We should have used this issue instead but I had forgotten its existence and the conversation happened on https://github.com/ampproject/wg-security-privacy/issues/2 instead.
