### ISSUE TITLE
List all AMP domain names and advise which ones will be transferred to the OpenJSF

### ISSUE THREAD

**Issue by tobie** [ampproject/wg-foundation-onboarding#3]
- [x] Decide whether AMP will maintain its own DNS. _No. The foundation will._
- [x] List which AMP related domain names are owned by google and which ones will be transferred to the OpenJSF.
    - ampproject.org (not transferred, see [disentanglement plan](https://docs.google.com/document/d/1IMfhVgxCRW0Cq1N7xvflfcoxGdnVshvA92je_wDxAY0/edit) as to why).
    - amp.dev (transferred).
- [x] Approve plan outlined in openjs-foundation/project-status#156
- [x] Inform operations@openjsf.org of the above.

_Note actual transfer happens post-graduation and is tracked in openjs-foundation/project-status#156._

**Comment by tobie** [comment]
/cc @mrjoro @sebastianbenz @ampproject/wg-codeofconduct 

Can you please figure out who to assign this too?

**Comment by mrjoro** [comment]
I'll assign to myself for now while we wait for the legal discussions to finalize.

For the actual mechanics of the transfer, I'm not sure who can handle that.  @sebastianbenz I know you were able to change some DNS settings--does that mean you have the power to do this as well?

**Comment by brianwarner** [comment]
This one should be pretty straightforward.  When the time comes, Linux Foundation IT just needs a transfer code.  We can either set up DNS to mirror what it is today, or delegate to a project-managed nameserver.  We'll transfer it into our master account, and then renewals are our responsibility from that point forward.

**Comment by sebastianbenz** [comment]
I can do the DNS related tasks on our side.@mrjoro are you going to request the transfer code? 

@brianwarner how are cert renewals going to be handled in the future? amp.dev currently requires a special SXG certificate which needs to be updated every 90 days. Not sure if that might be a problem.

**Comment by brianwarner** [comment]
Generally we get a two year wildcard cert, and then the project provisions it.  Does that work for you?

**Comment by sebastianbenz** [comment]
That works for the normal cert. However, in addition, we need a [SXG cert](https://amp.dev/documentation/guides-and-tutorials/optimize-and-measure/signed-exchange/#acquire-a-supported-tls-certificate) (which you can currently only obtain via Digicert and it needs to be renewed every 90 days).

**Comment by tobie** [comment]
Filed an issue here wrt SXG certs: https://github.com/openjs-foundation/project-onboarding/issues/32.

**Comment by tobie** [comment]
@Gregable, @sebastianbenz: can you please confirm that:

1. `amp.dev` will be transferred to the OpenJSF,
2. `ampproject.org` will not be transferred as per the [disentanglement plan](https://docs.google.com/document/d/1IMfhVgxCRW0Cq1N7xvflfcoxGdnVshvA92je_wDxAY0/edit), and
3. there are no other AMP-related Web properties currently owned or operated by Google.

Thanks!

**Comment by Gregable** [comment]
Yes on openjs-foundation/project-status#162. I can't speak to the others.

**Comment by tobie** [comment]
Confirmed in today's onboarding-WG call that there were no other AMP domain names owned or operated by Google and that only amp.dev was going to be transferred to the foundation.
